name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug Dependencies
      run: |
        pip list
        python --version

    - name: Check Environment Variables
      run: |
        echo "GMAIL_CLIENTID: ${{ secrets.GMAIL_CLIENTID }}"
        echo "GMAIL_CLIENTSECRET: ${{ secrets.GMAIL_CLIENTSECRET }}"

    - name: Run Script
      env:
        GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
        GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        GMAIL_CLIENTID: ${{ secrets.GMAIL_CLIENTID }}
        GMAIL_CLIENTSECRET: ${{ secrets.GMAIL_CLIENTSECRET }}
      run: |
        python main.py
